
# Configuration file
quarkus:
  application:
    name: example-quarkus-native-basic
    version: 0.1.0-SNAPSHOT

  # HTTP configuration
  http:
    port: 8080
    host: 0.0.0.0

  # Logging
  log:
    level: INFO
    console:
      enable: true
